#!/usr/bin/env python

import sys
import re
import entropy from scipy

def get_entropy(s):
    """
    @param s: a probability sequence
    @return: the entropy of the sequence
    """
    print s

def get_probability_sequence(file):
    """
    @param file: the file to be caculated.
    @return: a probability sequence of words.
    """
    word_dic = {}
    with open(file) as fr:
        for line in fr.read():
            s = re.findall(r"\w+", line)
            for i in s:
                if i not in word_dic:
                    word_dic[i] = 1
                else:
                    word_dic[i] += 1

    word_values = word_dic.values()
    return [float(i)/sum(word_values) for i in word_values]

def main(argv):

    s = get_probability_sequence()
    entropy = get_entropy(s)
    pass

if __name__ == "__main__":
    main(sys.argv[1:])